[project]
name = "milestone2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dash-bootstrap-components>=1.6.0",
    "dash>=2.18.2",
    "pandas>=2.2.3",
    "shap>=0.46.0",
    "pip>=24.3.1",
]
